project_name: gotlsaflare
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: gotlsaflare
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64